### ISSUE TITLE
stitch.py does not work with relative output paths

### ISSUE THREAD

**Issue by aryam7** [beelabhmc/flower_map#10]
@elissahou discovered that `stitch.py` doesn't work properly when the output path is relative instead of absolute. At the root of the problem is a bug within the Metashape Python API that prevents `doc.save()` from taking a relative path.

There are three potential ways of solving this:
1. Specify that the output path in `config.yml` must be absolute
2. Make the Snakefile provide an absolute path when it calls `stitch.py` and specify that `stitch.py` requires an absolute path
3. Within `stitch.py`, convert the output path to an absolute path at some point before using it in `doc.save()`

Solution 3 might be better, since it attacks the root problem without side-stepping around it. It will also allow people to use relative paths in `config.yml`

**For solutions 2 or 3**
One way to convert a relative path to an absolute path within python is to use [`os.path.abspath`](https://stackoverflow.com/a/51523). Another way (which uses the new, fancy `pathlib` module) is to use [`Path().resolve()`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve)

**Comment by mdonaldsonmatasci** [comment]
Yes, I like solution 3!
