### ISSUE TITLE
typeerror in transform.py

### ISSUE THREAD

**Issue by aryarm** [beelabhmc/flower_map#9]
```
Traceback (most recent call last):
  File "scripts/transform.py", line 91, in <module>
    [
  File "scripts/transform.py", line 92, in <listcomp>
    list(transform(chunk, camera, seg))
  File "scripts/transform.py", line 46, in transform
    pt = chunk.model.pickPoint(camera.center, camera.unproject(Metashape.Vector(point)))
TypeError: object is not a sequence
```
see [the code](https://github.com/beelabhmc/flower_map/blob/ab76eccafcc593965806009f42ac7fe2b7ec7063/scripts/transform.py#L46)

**Comment by aryam7** [comment]
seems like this is related to [this](https://www.agisoft.com/forum/index.php?topic=11897.0)

**Comment by aryam7** [comment]
I originally thought this error might be happening because the transform function isn't yielding any elements.

But I actually don't think that makes sense, anymore. The error is coming from a Metashape function: either `pickPoint`, `unproject`, or `Metashape.Vector`

**Comment by aryam7** [comment]
@elissahou if you're not still getting this error, feel free to close this issue

**Comment by tommyfuu** [comment]
Yes, I am still getting this error haha.

**Comment by aryarm** [comment]
for posterity:
further debugging of this issue led us to the conclusion that the images in the particular dataset that was used in this situation led to a fragmented orthomosaic
so the orthomosaic was the underlying problem
I'm going to close this issue for now, but if anyone encounters this issue again, please reopen it!
